name: hamazh_auth
description: "hamazh auth test"

publish_to: 'HamazhCLL'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0
  firebase_auth: ^4.8.0
  firebase_core: ^2.22.0
  animations: ^2.0.7
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  country_code_picker: ^3.0.0
  #local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/image/



